### ISSUE TITLE
Agent sometimes doesn't have a move to make after reaching the gold

### ISSUE THREAD

**Issue by r-luong** [Darkrunes/Machine-Neural-Pruning-MCTS-Mario#1]
On maps with lots of walls such as s2 and s3. The agent is able to successfully reach the gold but sometimes it gets stuck and has no move to make. For some reason it thinks the gold is still on the map while it is holding the gold. The temporary solution to this was to priority to return the starting point if the Agent is holding the gold in the getGoal() method of the GetGold Behaviour. **_This problem hasn't occurred anymore because of this but it still thinks the gold is on the map after picking it up but I just wanted to take a note of it._**

**Comment by Darkrunes** [comment]
In input2 removing the visited list and moving the gold check back where it was, fixs the problem. Based on the output a lot of backtracking was made to find a solution, ~800 moves in this state. The current version with the gold check first and visited list does the game in ~580 moves. 

Keeping the visited list and increasing max node expansion completed the game successfully in ~330 moves. The Problem seems to be with 2000 moves as a max limit its not that the game doesn't detect gold rather it cant find a path to the start.

Edit:
Following assumes visited list is kept. Tested on s2
Having the gold check first, with a max iteration of 5000 results in ~800 moves to complete the game.
Having the gold check last (like before), with a max iteration of 5000 results in ~300 moves

Edit2:
Fuck. Seems to get stuck at gold if the gold check is last 50% of the time

Edit3:
What... the... fuck... 
Visited list + 5000 iterations + s2 + gold check first = ~300 moves now and consistently solves the problem...
